inicio/urls.py
from django.urls import path
from .views import *

app_name = 'inicio'

urlpatterns = [
    path('', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('lista_vehiculos/', ListaVehiculosView.as_view(), name='lista_vehiculos'),
    path('agregar_vehiculo/', AgregarVehiculoView.as_view(), name='agregar_vehiculo'),
    path('editar_vehiculo/<int:id_vehiculo>/', EditarVehiculoView.as_view(), name='editar_vehiculo'),
    path('eliminar_vehiculo/<int:id_vehiculo>/', EliminarVehiculoView.as_view(), name='eliminar_vehiculo'),
    path('detalle_vehiculo/<int:id_vehiculo>/', DetalleVehiculoView.as_view(), name='detalle_vehiculo'),
    path('lista_quejas/', ListaQuejasView.as_view(), name='lista_quejas'),
    path('agregar_queja/', AgregarQuejaView.as_view(), name='agregar_queja'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/models.py
from django.db import models

class Vehiculo(models.Model):
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    anio = models.IntegerField()
    imagen = models.ImageField(upload_to='vehiculos/', null=True, blank=True)
    descripcion = models.TextField(default='Sin descripcion')

    def __str__(self):
        return f"{self.marca} {self.modelo} ({self.anio})"



class Queja(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    queja = models.TextField()

inicio/forms.py
from django import forms
from .models import Vehiculo, Queja

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ('marca', 'modelo', 'anio', 'imagen', 'descripcion')

class QuejaForm(forms.ModelForm):
    class Meta:
        model = Queja
        fields = ['queja']

class BusquedaVehiculoForm(forms.Form):
    marca = forms.CharField(required=False)
    modelo = forms.CharField(required=False)
    anio = forms.IntegerField(required=False)

inicio/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import Template, Context, loader, RequestContext
from inicio.models import Vehiculo, Queja
from django.shortcuts import render, redirect, get_object_or_404
from inicio.forms import VehiculoForm, QuejaForm, BusquedaVehiculoForm
from django.views import View
from django.contrib.auth.mixins import UserPassesTestMixin


class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser

class IndexView(View):
    def get(self, request):
        return render(request, 'inicio/index.html')

class AboutView(View):
    def get(self, request):
        return render(request, 'inicio/about.html')

class ListaVehiculosView(View):
    def get(self, request):
        vehiculos = Vehiculo.objects.all()
        form = BusquedaVehiculoForm(request.GET)
        if form.is_valid():
            marca = form.cleaned_data['marca']
            modelo = form.cleaned_data['modelo']
            anio = form.cleaned_data['anio']
            
            if marca:
                vehiculos = vehiculos.filter(marca__icontains=marca)
            if modelo:
                vehiculos = vehiculos.filter(modelo__icontains=modelo)
            if anio:
                vehiculos = vehiculos.filter(anio=anio)
        
        context = {
            'form': form,
            'vehiculos': vehiculos,
        }
        return render(request, 'inicio/lista_vehiculos.html', context)

class AgregarVehiculoView(SuperuserRequiredMixin, View):
    def get(self, request):
        formulario = VehiculoForm()
        return render(request, 'inicio/agregar_vehiculo.html', {'formulario': formulario})

    def post(self, request):
        formulario = VehiculoForm(request.POST, request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect('inicio:lista_vehiculos')
        return render(request, 'inicio/agregar_vehiculo.html', {'formulario': formulario})

class EditarVehiculoView(SuperuserRequiredMixin, View):
    def get(self, request, id_vehiculo):
        vehiculo = get_object_or_404(Vehiculo, id=id_vehiculo)
        formulario = VehiculoForm(instance=vehiculo)
        return render(request, 'inicio/editar_vehiculo.html', {'formulario': formulario, 'id_vehiculo': id_vehiculo})

    def post(self, request, id_vehiculo):
        vehiculo = get_object_or_404(Vehiculo, id=id_vehiculo)
        formulario = VehiculoForm(request.POST, request.FILES, instance=vehiculo)
        if formulario.is_valid():
            formulario.save()
            return redirect('inicio:lista_vehiculos')
        return render(request, 'inicio/editar_vehiculo.html', {'formulario': formulario, 'id_vehiculo': id_vehiculo})

class EliminarVehiculoView(SuperuserRequiredMixin, View):
    def get(self, request, id_vehiculo):
        vehiculo = get_object_or_404(Vehiculo, id=id_vehiculo)
        return render(request, 'inicio/eliminar_vehiculo.html', {'vehiculo': vehiculo})
    
    def post(self, request, id_vehiculo):
        vehiculo = get_object_or_404(Vehiculo, id=id_vehiculo)
        vehiculo.delete()
        return redirect('inicio:lista_vehiculos')

class DetalleVehiculoView(View):
    def get(self, request, id_vehiculo):
        vehiculo = get_object_or_404(Vehiculo, id=id_vehiculo)
        return render(request, 'inicio/detalle_vehiculo.html', {'vehiculo': vehiculo})

class ListaQuejasView(View):
    def get(self, request):
        quejas = Queja.objects.all()
        return render(request, 'inicio/lista_quejas.html', {'quejas': quejas})

class AgregarQuejaView(View):
    def get(self, request):
        form = QuejaForm()
        context = {'form': form}
        return render(request, 'inicio/agregar_queja.html', context)
    
    def post(self, request):
        form = QuejaForm(request.POST)
        if form.is_valid():
            queja = form.save(commit=False)
            queja.save()
            return redirect('inicio:lista_quejas')
        context = {'form': form}
        return render(request, 'inicio/agregar_queja.html', context)

inicio/templates/inicio/about.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>about</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Un poco sobre mi</h1>
{% endblock h1_header %}

{% block contenido %}
<br> Soy Martinez Christian, curso la Tecnicatura de Analista de Sistemas en el I.S.F.T 179 de Moreno, y tambien estoy terminando el curso de Python en CoderHouse, este es mi trabajo final en él. </br>
<br> Mi perfil de LinkedIn es: https://www.linkedin.com/in/christian-tomas-mart%C3%ADnez-villagra-39a71223a/ </br>
<br> Mi perfil de GitHub es: https://github.com/christiantomasmartinez </br>
{% endblock contenido %}

inicio/templates/inicio/agregar_queja.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Agregar Queja</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Agregar Queja</h1>
{% endblock h1_header %}

{% block contenido %}
<form method="POST">
  {% csrf_token %}
  {% if not user.is_authenticated %}
    <div>
      <label for="nombre_usuario">Nombre de Usuario (opcional):</label>
      <input type="text" id="nombre_usuario" name="nombre_usuario">
    </div>
  {% endif %}
  <div>
    <label for="queja">Queja:</label>
    <textarea id="queja" name="queja" required></textarea>
  </div>
  <button type="submit">Enviar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/agregar_vehiculo.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Agregar vehiculo al listado</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Agregue el vehiculo</h1>
{% endblock h1_header %}

{% block contenido %}
<form action="{% url 'inicio:agregar_vehiculo' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <button type="submit">Agregar vehiculo</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/detalle_vehiculo.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Detalle del Vehículo</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Detalle del Vehículo</h1>
{% endblock h1_header %}

{% block contenido %}
    <div>
        <h3>Marca: {{ vehiculo.marca }}</h3>
        <h3>Modelo: {{ vehiculo.modelo }}</h3>
        <h3>Año: {{ vehiculo.anio }}</h3>
        {% if vehiculo.descripcion %}
            <p>Descripción: {{ vehiculo.descripcion }}</p>
        {% endif %}
        {% if vehiculo.imagen %}
            <img src="{{ vehiculo.imagen.url }}" alt="Imagen del vehículo" style="max-width: 750px;">
        {% else %}
            <p>No hay imagen disponible</p>
        {% endif %}
    </div>
{% endblock contenido %}

inicio/templates/inicio/editar_vehiculo.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Modificar vehículo</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Modificar vehículo</h1>
{% endblock h1_header %}

{% block contenido %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formulario.as_p }}
    <button type="submit">Guardar cambios</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/eliminar_vehiculo.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Eliminar vehículo</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Eliminar vehículo</h1>
{% endblock h1_header %}

{% block contenido %}
<p>¿Está seguro de que desea eliminar el siguiente vehículo?</p>

<table>
    <tr>
        <th>Marca</th>
        <td>{{ vehiculo.marca }}</td>
    </tr>
    <tr>
        <th>Modelo</th>
        <td>{{ vehiculo.modelo }}</td>
    </tr>
    <tr>
        <th>Kilometraje</th>
        <td>{{ vehiculo.kilometraje }}</td>
    </tr>
</table>

<form action="{% url 'inicio:eliminar_vehiculo' vehiculo.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/index.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Bienvenidos a la concesionaria Pepito</h1>
{% endblock h1_header %}

inicio/templates/inicio/lista_quejas.html
{% extends 'genericos/base.html' %}

{% block title_head %}

  <title>Lista de Quejas</title>
{% endblock title_head %}
{% block h1_header %}

  <h1>Lista de Quejas</h1>
{% endblock h1_header %}
{% block contenido %}

  <ul>
    {% for queja in quejas %}
      <li>
        {% if queja.nombre_usuario %}
          <strong>Usuario:</strong> {{ queja.nombre_usuario }}<br>
        {% endif %}
        <strong>Fecha de creación:</strong> {{ queja.fecha_creacion|date:"d/m/Y" }}<br>
        <strong>Queja:</strong> {{ queja.queja }}<br>
      </li>
    {% empty %}
      <li>No hay quejas.</li>
    {% endfor %}
  </ul>
{% endblock contenido %}

inicio/templates/inicio/lista_vehiculos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Lista de Vehículos</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Lista de Vehículos</h1>
{% endblock h1_header %}

{% block contenido %}
    <form method="GET">
        <label for="marca">Marca:</label>
        <input type="text" name="marca" id="marca" value="{{ request.GET.marca }}">
        <label for="modelo">Modelo:</label>
        <input type="text" name="modelo" id="modelo" value="{{ request.GET.modelo }}">
        <label for="anio">Año:</label>
        <input type="text" name="anio" id="anio" value="{{ request.GET.anio }}">
        <button type="submit">Buscar</button>
        {% if request.GET %}
            <a href="{% url 'inicio:lista_vehiculos' %}">Limpiar búsqueda</a>
        {% endif %}
    </form>
    
    <table>
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Año</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for vehiculo in vehiculos %}
                <tr>
                    <td>{{ vehiculo.marca }}</td>
                    <td>{{ vehiculo.modelo }}</td>
                    <td>{{ vehiculo.anio }}</td>
                    <td>
                        <a href="{% url 'inicio:detalle_vehiculo' id_vehiculo=vehiculo.id %}">Ver más</a>
                        {% if request.user.is_superuser %}
                            <form action="{% url 'inicio:editar_vehiculo' vehiculo.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit">Editar</button>
                            </form>
                            <form action="{% url 'inicio:eliminar_vehiculo' vehiculo.pk %}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit">Eliminar</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">No hay vehículos registrados.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

inicio/templates/inicio/registrar_vehiculo.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Agregar vehiculo al listado</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Agregue el vehiculo</h1>
{% endblock h1_header %}

{% block contenido %}
<form action="{% url 'inicio:registrar_vehiculo' %}" method="POST">
    {% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <button type="submit">Agregar vehiculo</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/registro_exitoso.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>REGISTRO EXITOSO!</h1>
{% endblock h1_header %}