inicio/urls.py
from django.urls import path
from .views import *

app_name = 'inicio'

urlpatterns = [
    path('', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('lista_vehiculos/', ListaVehiculosView.as_view(), name='lista_vehiculos'),
    path('agregar_vehiculo/', AgregarVehiculoView.as_view(), name='agregar_vehiculo'),
    path('editar_vehiculo/<int:id_vehiculo>/', EditarVehiculoView.as_view(), name='editar_vehiculo'),
    path('eliminar_vehiculo/<int:id_vehiculo>/', EliminarVehiculoView.as_view(), name='eliminar_vehiculo'),
    path('detalle_vehiculo/<int:id_vehiculo>/', DetalleVehiculoView.as_view(), name='detalle_vehiculo'),
    path('lista_quejas/', ListaQuejasView.as_view(), name='lista_quejas'),
    path('agregar_queja/', AgregarQuejaView.as_view(), name='agregar_queja'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_contrasenia', views.CambiarContrasenia.as_view(), name='cambiar_contrasenia'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('perfil/<str:username>/', views.perfil_usuario, name='perfil'),
    path('perfil/<str:username>/editar_descripcion/', views.editar_descripcion, name='editar_descripcion'),
    path('perfil/<str:username>/editar_enlace/', views.editar_enlace, name='editar_enlace'),
]

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:lista_vehiculos' %}>Buscar un vehiculo</a>
                {% if request.user.is_superuser %}
                <a class="navbar-brand" href={% url 'inicio:agregar_vehiculo' %}>Agregar vehiculo</a>
                {% endif %}
                {% if request.user.is_authenticated %}
                <div class="user-info">
                    <a class="navbar-brand" href={% url 'usuarios:editar_perfil' %}>Editar Perfil</a>
                    <a href="{% url 'usuarios:perfil' username=request.user.username %}" class="btn btn-primary">Ver perfil</a>
                    {% if request.user.infoextra.avatar %}
                    <img src="{{ request.user.infoextra.avatar.url }}" width="35" height="35">
                    {% else %}
                        <img src="{{ request.user.infoextra.avatar_thumbnail.url }}" width="35" height="35">
                    {% endif %}
                </div>
                <a class="btn btn-primary" href={% url 'usuarios:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuarios:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuarios:registro' %}>Registrarse</a>
            </div>
            {% endif %}
        </nav>
        <!-- Masthead-->
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block h1_header %}
                            <h1 class="mb-5">Bienvenidos a la concesionaria Pepito</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="list-inline-item" href={% url 'inicio:agregar_queja' %}>Agregar Queja</a>
                        </li>
                        <li class="nav-item">
                            <a class="list-inline-item" href={% url 'inicio:lista_quejas' %}>Lista Quejas</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="list-inline-item" href={% url 'inicio:about' %}>About</a>
                        </li>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'inicio/js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>