inicio/urls.py
from django.urls import path
from .views import *

app_name = 'inicio'

urlpatterns = [
    path('', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('lista_vehiculos/', ListaVehiculosView.as_view(), name='lista_vehiculos'),
    path('agregar_vehiculo/', AgregarVehiculoView.as_view(), name='agregar_vehiculo'),
    path('editar_vehiculo/<int:id_vehiculo>/', EditarVehiculoView.as_view(), name='editar_vehiculo'),
    path('eliminar_vehiculo/<int:id_vehiculo>/', EliminarVehiculoView.as_view(), name='eliminar_vehiculo'),
    path('detalle_vehiculo/<int:id_vehiculo>/', DetalleVehiculoView.as_view(), name='detalle_vehiculo'),
    path('lista_quejas/', ListaQuejasView.as_view(), name='lista_quejas'),
    path('agregar_queja/', AgregarQuejaView.as_view(), name='agregar_queja'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_contrasenia', views.CambiarContrasenia.as_view(), name='cambiar_contrasenia'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('perfil/<str:username>/', views.perfil_usuario, name='perfil'),
    path('perfil/<str:username>/editar_descripcion/', views.editar_descripcion, name='editar_descripcion'),
    path('perfil/<str:username>/editar_enlace/', views.editar_enlace, name='editar_enlace'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    descripcion = models.TextField(blank=True)
    enlace_pagina = models.URLField(blank=True)
    avatar_thumbnail = models.ImageField(upload_to='avatares/', default='avatares/default_thumbnail.png')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            img = Image.open(self.avatar.path)
            output_size = (35, 35)
            img.thumbnail(output_size)
            img.save(self.avatar.path)
            img.save(self.avatar_thumbnail.path)

    def __str__(self):
        return self.user.username

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from usuarios.models import InfoExtra


class FormularioRegistro(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: '' for k in fields}


class EdicionPerfil(UserChangeForm):
    password = None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre', max_length=30)
    last_name = forms.CharField(label='Apellido', max_length=30)

    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'avatar']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'multiple': False}),
        }
        labels = {
            'avatar': 'Imagen de perfil',
        }
        help_texts = {
            'avatar': 'Ingrese una imagen para su perfil (opcional)',
        }
        error_messages = {
            'avatar': {
                'invalid': "Formato de imagen no soportado. Solo se permiten los formatos JPG, PNG, y GIF.",
            }
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            info_extra = InfoExtra.objects.get(user=self.instance)
            self.fields['avatar'].initial = info_extra.avatar
        except InfoExtra.DoesNotExist:
            pass

    def save(self, commit=True):
        user = super().save(commit=commit)
        try:
            info_extra = InfoExtra.objects.get(user=user)
        except InfoExtra.DoesNotExist:
            info_extra = InfoExtra(user=user)
        if self.cleaned_data.get('avatar'):
            info_extra.avatar = self.cleaned_data.get('avatar')
        info_extra.save()
        return user

class DescripcionForm(forms.ModelForm):
    class Meta:
        model = InfoExtra
        fields = ['descripcion']
        labels = {'descripcion': 'Descripción'}

class EnlaceForm(forms.ModelForm):
    class Meta:
        model = InfoExtra
        fields = ['enlace_pagina']
        labels = {'enlace_pagina': 'Enlace a la página'}

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as login_django
from usuarios.forms import FormularioRegistro, EdicionPerfil, DescripcionForm, EnlaceForm
from django.contrib.auth.decorators import login_required
from usuarios.models import InfoExtra
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin



def login(request):
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
            user = authenticate(username=usuario, password=contrasenia)
            login_django(request, user)
            InfoExtra.objects.get_or_create(user=user)
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuarios/login.html', {'form': formulario})
    formulario = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'form': formulario})


def registro(request):
    if request.method == 'POST':
        formulario = FormularioRegistro(request.POST)
        if formulario.is_valid():
            usuario = formulario.save()
            InfoExtra.objects.get_or_create(user=usuario)
            return redirect('usuarios:login')
        else:
            return render(request, 'usuarios/registro.html', {'form': formulario})
    formulario = FormularioRegistro()
    return render(request, 'usuarios/registro.html', {'form': formulario})


@login_required
def editar_perfil(request):
    if request.method == 'POST':
        formulario = EdicionPerfil(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            formulario.save()
            infoextra = request.user.infoextra
            if 'avatar' in request.FILES:
                infoextra.avatar = request.FILES['avatar']
            infoextra.save()
            return redirect('usuarios:editar_perfil')
        else:
            return render(request, 'usuarios/editar_perfil.html', {'form': formulario})
    formulario = EdicionPerfil(instance=request.user)
    return render(request, 'usuarios/editar_perfil.html', {'form': formulario})


class CambiarContrasenia(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_contrasenia.html'
    success_url = reverse_lazy('usuarios:editar_perfil')



@login_required
def perfil_usuario(request, username):
    perfil = get_object_or_404(InfoExtra, user__username=username)
    return render(request, 'usuarios/perfil.html', {'perfil': perfil})


def editar_descripcion(request, username):
    perfil = get_object_or_404(InfoExtra, user__username=username)

    if request.method == 'POST':
        form = DescripcionForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            return redirect('usuarios:perfil', username=username)
    else:
        form = DescripcionForm(instance=perfil)

    return render(request, 'usuarios/editar_descripcion.html', {'form': form})

from django.shortcuts import render, redirect, get_object_or_404
from .forms import DescripcionForm, EnlaceForm
from usuarios.models import InfoExtra


def editar_enlace(request, username):
    perfil = get_object_or_404(InfoExtra, user__username=username)

    if request.method == 'POST':
        form = EnlaceForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            return redirect('usuarios:perfil', username=username)
    else:
        form = EnlaceForm(instance=perfil)

    return render(request, 'usuarios/editar_enlace.html', {'form': form})

usuarios/templates/usuarios/cambiar_contrasenia.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Cambiar Contrasenia</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Cambiar Contrasenia</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.error %}
<p>Formulario invalido</p>
{% endif %}

<form action={% url 'usuarios:cambiar_contrasenia' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Cambiar</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/editar_descripcion.html
{% extends 'genericos/base.html' %}

{% block contenido %}
  <h2>Editar Descripción</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

usuarios/templates/usuarios/editar_enlace.html
{% extends 'genericos/base.html' %}

{% block contenido %}
  <h2>Editar Enlace</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

usuarios/templates/usuarios/editar_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Editar perfil</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Editar perfil</h1>
{% endblock h1_header %}

{% block contenido %}
{% if form.errors %}
<p>Formulario invalido</p>
{% endif %}

<form action="{% url 'usuarios:editar_perfil' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="button"><a href="{% url 'usuarios:cambiar_contrasenia' %}">Cambiar Contraseña</a></button>
    <button type="submit">Editar</button>
</form>

{% endblock contenido %}

usuarios/templates/usuarios/login.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Login</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.error %}
<p>Credenciales invalidas</p>
{% endif %}


<form action={% url 'usuarios:login' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Loguearse</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/logout.html
{% extends 'genericos/base.html' %}


{% block title_head %}
<title>Logout</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Te deslogueaste con exito!!</h1>
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

usuarios/templates/usuarios/perfil.html
{% extends 'genericos/base.html' %}

{% block title %}Perfil - {{ perfil.user.username }}{% endblock %}

{% block contenido %}
<div>
      {% if request.user.infoextra.avatar %}
      <h2>Perfil de {{ perfil.user.username }} <img src="{{ perfil.avatar.url }}" alt="Foto de perfil"></h2>
      {% else %}
      <h2>Perfil de {{ perfil.user.username }}</h2>
      {% endif %}
    <p>Nombre: {{ perfil.user.first_name }} {{ perfil.user.last_name }}</p>
    <p>Email: {{ perfil.user.email }}</p>
    <p>Descripción: {{ perfil.descripcion }}</p>
    <p>Enlace a la página: <a href="{{ perfil.enlace_pagina }}">{{ perfil.enlace_pagina }}</a></p>
    {% if request.user == perfil.user %}
      <a href="{% url 'usuarios:editar_descripcion' perfil.user.username %}" class="btn btn-primary">Editar Descripción</a>
      <a href="{% url 'usuarios:editar_enlace' perfil.user.username %}" class="btn btn-primary">Editar Enlace</a>
    {% endif %}
  </div>
{% endblock %}

usuarios/templates/usuarios/registro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Registrarse</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.error %}
<p>Datos invalidos</p>
{% endif %}
<form action={% url 'usuarios:registro' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Registrarse</button>
</form>

{% endblock contenido %}